declare namespace NodeJS {
	interface ProcessEnv {
		NEXT_PUBLIC_PUBLIC_KEY: string
		NEXT_PUBLIC_SERVICE_ID: string
		NEXT_PUBLIC_TEMPLATE_SUBSCRIPTION_ID: string
		NEXT_PUBLIC_TEMPLATE_MESSAGE_ID: string
		NEXT_PUBLIC_MAPBOX_API_KEY: string
		NEXT_PUBLIC_API_URL: string
	}
}
