import postImage from '@/assets/postImage.png'

export const postsData = [
	{
		id: 0,
		image: postImage,
		category: 'Startup',
		title: 'Design tips for designers that cover everything you need',
		text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
	},
	{
		id: 1,
		image: postImage,
		category: 'Startup',
		title: 'Design tips for designers that cover everything you need',
		text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
	},
	{
		id: 2,
		image: postImage,
		category: 'Startup',
		title: 'Design tips for designers that cover everything you need',
		text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
	},
	{
		id: 3,
		image: postImage,
		category: 'Startup',
		title: 'Design tips for designers that cover everything you need',
		text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
	},
	{
		id: 4,
		image: postImage,
		category: 'Startup',
		title: 'Design tips for designers that cover everything you need',
		text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
	},
	{
		id: 5,
		image: postImage,
		category: 'Startup',
		title: 'Design tips for designers that cover everything you need',
		text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
	},
	{
		id: 7,
		image: postImage,
		category: 'Build',
		title: 'Design tips for designers that cover everything you need',
		text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
	},
	{
		id: 8,
		image: postImage,
		category: 'Build',
		title: 'Design tips for designers that cover everything you need',
		text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
	},
	{
		id: 9,
		image: postImage,
		category: 'Build',
		title: 'Design tips for designers that cover everything you need',
		text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
	},
	{
		id: 10,
		image: postImage,
		category: 'Build',
		title: 'Design tips for designers that cover everything you need',
		text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
	},
	{
		id: 11,
		image: postImage,
		category: 'Build',
		title: 'Design tips for designers that cover everything you need',
		text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
	},
	{
		id: 12,
		image: postImage,
		category: 'Build',
		title: 'Design tips for designers that cover everything you need',
		text: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
	},
]
